import type { Metadata } from "next";
import { Istok_Web, Piazzolla } from "next/font/google";
import { ReactLenis } from "lenis/react";
import "./globals.css";

const istockWeb = Istok_Web({
  weight: ["400", "700"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-istok-web",
});

const piazzolla = Piazzolla({
  subsets: ["latin", "latin-ext"],
  variable: "--font-piazzolla",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pl-PL"
      className={`h-full ${istockWeb.variable} ${piazzolla.variable} antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReactLenis root options={{ lerp: 0.05, duration: 0.3 }}>
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
